Repository omni-network/omni, pull requests merged in 2024-10, with the labels that each got.

#2021 ci(goreleaser): multiarch external releases
  .github/workflows/clicommand.yml
  .github/workflows/pr-e2etest.yml
  .github/workflows/release-official.yml
  .github/workflows/release-snapshot.yml
  .goreleaser-official.yaml
  .goreleaser-snapshot.yaml
  .goreleaser.yaml
  Makefile
Labels: release/v0.8

#2039 chore(halo): start RPCs before comet
  halo/app/start.go
  halo/cmd/cometconfig.go
  halo/cmd/testdata/TestCLIReference_rollback.golden
  halo/cmd/testdata/TestCLIReference_run.golden
  halo/cmd/testdata/TestRunCmd_defaults.golden
  halo/cmd/testdata/TestRunCmd_flags.golden
  halo/cmd/testdata/TestRunCmd_json_files.golden
  halo/cmd/testdata/TestRunCmd_toml_files.golden
  halo/config/config.go
  halo/config/testdata/default_halo.toml
Labels: release/v0.8

#2057 chore(lib/cmd): improve invalid command errors
  e2e/app/rpc.go
  halo/cmd/cmd_internal_test.go
  halo/cmd/testdata/TestCLIReference_halo.golden
  lib/cmd/cmd.go
Labels: release/v0.8

#2088 fix(lib/cmd): fix missing cli errors
  e2e/cmd/cmd.go
  halo/cmd/cmd_internal_test.go
  halo/cmd/testdata/TestRunCmd_json_files.golden
  lib/cmd/cmd.go
Labels: bug, backport-to:release/v0.9

#2117 fix(octane/keeper): retry fecthing evm event logs
  octane/evmengine/keeper/abci.go
  octane/evmengine/keeper/evmmsgs.go
  octane/evmengine/keeper/helpers.go
  octane/evmengine/keeper/msg_server.go
  octane/evmengine/keeper/proposal_server.go
Labels: bug

#2120 fix(provider): potential nil pointer dereference
  lib/cchain/provider/xblock.go
  lib/cchain/provider/xblock_internal_test.go
Labels: stale-pr

#2137 fix(xchain): add signature validation
  halo/attest/types/tx.go
Labels: stale-pr

#2287 test(contracts/core): replaced TS helpers with XSubGen
  contracts/core/.gas-snapshot
  contracts/core/package.json
  contracts/core/test/templates/OmniPortal.t.sol
  contracts/core/test/utils/XSubGen.sol
  contracts/core/test/xchain/OmniPortal_admin.t.sol
  contracts/core/test/xchain/OmniPortal_sys.t.sol
  contracts/core/test/xchain/OmniPortal_xsubmit.t.sol
  contracts/core/test/xchain/OmniPortal_xsubmit_gas.t.sol
  contracts/core/test/xchain/common/Fixtures.sol
  contracts/core/test/xchain/data/xblocks.json
  contracts/core/test/xchain/data/xblocks_decoded.json
  contracts/core/test/xchain/data/xsubs.json
  contracts/core/test/xchain/data/xsubs_decoded.json
  contracts/core/test/xchain/script/WriteTestXBlocks.s.sol
  contracts/core/test/xchain/ts/abis.ts
  contracts/core/test/xchain/ts/merkle.ts
  contracts/core/test/xchain/ts/script/genxsubs/io.ts
  contracts/core/test/xchain/ts/script/genxsubs/main.ts
  contracts/core/test/xchain/ts/script/genxsubs/types.ts
  contracts/core/test/xchain/ts/script/genxsubs/utils.ts
  contracts/core/test/xchain/ts/xtypes.ts
Labels: good first issue
